#!/bin/bash

make clean
make

#T1 = "valgrind"
#T2 = "gdb"
if [[ "$2" == 1 || "$1" == 1 ]];
then
	sudo rm -r rvm_segments
	if [[ -z "$1" || "$1" == 1 ]];
	then
		./basic1

	elif [ "$1" == "valgrind" ];
	then
		valgrind ./basic1

	elif [ "$1" == "gdb" ];
	then
		gdb ./basic1
	fi
elif [[ "$2" == 2 || "$1" == 2 ]];
then
	if [[ -z "$1" || "$1" == 2 ]];
	then
		./basic2

	elif [ "$1" == "valgrind" ];
	then
		valgrind ./basic2

	elif [ "$1" == "gdb" ];
	then
		gdb ./basic2
	fi
fi
